name: ml_gcp
channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - flask
  - flask-oauthlib
  - numpy
  - pandas
  - pip
  - pydantic
  - pydantic-settings
  - python=3.12
  - sqlalchemy
  - loguru
  - scikit-learn
  - bcrypt
  - wtforms
  - psycopg2
  - humanfriendly
  - xgboost
  - bayesian-optimization
  - ipykernel
  - matplotlib
  - cachetools
  - pip:
      - annotated-types==0.7.0
      - appnope==0.1.4
      - asttokens==3.0.0
      - Authlib==1.4.0
      - bayesian-optimization==2.0.3
      - bcrypt==4.2.1
      - blinker==1.9.0
      - Brotli==1.1.0
      - cachelib==0.13.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - cryptography==44.0.0
      - debugpy==1.8.11
      - decorator==5.1.1
      - Deprecated==1.2.15
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - flake8==7.1.1
      - Flask==3.1.0
      - Flask-JWT-Extended==4.7.1
      - Flask-Limiter==3.10.0
      - Flask-Login==0.6.3
      - Flask-OAuthlib==0.9.6
      - Flask-SQLAlchemy==3.1.1
      - flask-talisman==1.1.0
      - Flask-WTF==1.2.2
      - greenlet==3.1.1
      - h2==4.1.0
      - hpack==4.0.0
      - humanfriendly==10.0
      - hyperframe==6.0.1
      - idna==3.10
      - importlib_metadata==8.5.0
      - ipykernel==6.29.5
      - ipython==8.31.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - Jinja2==3.1.5
      - joblib==1.4.2
      - jupyter_client==8.6.3
      - jupyter_core==5.7.2
      - limits==4.0.0
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - MarkupSafe==3.0.2
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - nest_asyncio==1.6.0
      - numpy==2.2.1
      - oauthlib==2.1.0
      - ordered-set==4.1.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pip==24.3.1
      - platformdirs==4.3.6
      - prompt_toolkit==3.0.48
      - psutil==6.1.1
      - psycopg2==2.9.9
      - ptyprocess==0.7.0
      - pure_eval==0.2.3
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic_core==2.27.2
      - pydantic-settings==2.7.1
      - pyflakes==3.2.0
      - Pygments==2.19.1
      - PyJWT==2.10.1
      - PySocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyzmq==26.2.0
      - requests==2.32.3
      - requests-oauthlib==1.1.0
      - rich==13.9.4
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - setuptools==75.8.0
      - six==1.17.0
      - SQLAlchemy==2.0.37
      - stack_data==0.6.3
      - threadpoolctl==3.5.0
      - tornado==6.4.2
      - traitlets==5.14.3
      - typing_extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - Werkzeug==3.1.3
      - wheel==0.45.1
      - wrapt==1.17.2
      - WTForms==3.2.1
      - xgboost==2.1.3
      - zipp==3.21.0
      - zstandard==0.23.0
